name: Amazon Price Monitor

on:

  schedule:
    - cron: '0 5 * * *'

  workflow_dispatch:

jobs:

  monitor:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"

      - name: Install Dependencies

        run: |
          pip install -r requirements.txt

      - name: Run Monitor

        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

        run: |
          python monitor.py